--- #YAML:1.0
name:               Dancer-Plugin-DetectRobots
version:            0.1
abstract:           ~
author:
    - Dan Busarow <dan@buildingonline.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:               1.175
    Regexp::Assemble:     0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
